apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: word-press-app

spec:
  storageClassName: manual

  volumeName: wordpress-pv

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi

